### ISSUE TITLE
Missing bak file

### ISSUE THREAD

**Issue by spekoun** [MicrosoftDocs/mslearn-sql-server-discovery-using-map#3]
Hello,

I am not able to download the MAP_updatedDB.bak file. Every time I received error code 404. Could you please check if the file is not corrupt?
Thank you.

Michal

**Comment by sql-aus-hh** [comment]
This is still open... sorry today
@PhilStollery please take a look into this... we are not able to download and proceed in the execises

**Comment by Psyflex83** [comment]
This is still not resolved ...

**Comment by shadmehr** [comment]
Same issue here! As a workaround, you could download the code master branch code and then extract it to find the backup file.

**Comment by PhilStollery** [comment]
No idea what happened to the file - uploaded again and it should work now.
